// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// TStarFastTiesRCPP
Rcpp::NumericVector TStarFastTiesRCPP(NumericVector xNumeric, NumericVector yNumeric);
RcppExport SEXP TauStar_TStarFastTiesRCPP(SEXP xNumericSEXP, SEXP yNumericSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type xNumeric(xNumericSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yNumeric(yNumericSEXP);
    __result = Rcpp::wrap(TStarFastTiesRCPP(xNumeric, yNumeric));
    return __result;
END_RCPP
}
// VTStarFastTiesRCPP
Rcpp::NumericVector VTStarFastTiesRCPP(NumericVector xNumeric, NumericVector yNumeric);
RcppExport SEXP TauStar_VTStarFastTiesRCPP(SEXP xNumericSEXP, SEXP yNumericSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type xNumeric(xNumericSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yNumeric(yNumericSEXP);
    __result = Rcpp::wrap(VTStarFastTiesRCPP(xNumeric, yNumeric));
    return __result;
END_RCPP
}
// TStarFastResampleRCPP
Rcpp::NumericVector TStarFastResampleRCPP(NumericVector xNumeric, NumericVector yNumeric, int numResamples, int sampleSize);
RcppExport SEXP TauStar_TStarFastResampleRCPP(SEXP xNumericSEXP, SEXP yNumericSEXP, SEXP numResamplesSEXP, SEXP sampleSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type xNumeric(xNumericSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yNumeric(yNumericSEXP);
    Rcpp::traits::input_parameter< int >::type numResamples(numResamplesSEXP);
    Rcpp::traits::input_parameter< int >::type sampleSize(sampleSizeSEXP);
    __result = Rcpp::wrap(TStarFastResampleRCPP(xNumeric, yNumeric, numResamples, sampleSize));
    return __result;
END_RCPP
}
// TStarSlowTiesRCPP
Rcpp::NumericVector TStarSlowTiesRCPP(NumericVector x, NumericVector y, bool vStat);
RcppExport SEXP TauStar_TStarSlowTiesRCPP(SEXP xSEXP, SEXP ySEXP, SEXP vStatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type vStat(vStatSEXP);
    __result = Rcpp::wrap(TStarSlowTiesRCPP(x, y, vStat));
    return __result;
END_RCPP
}
