# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TStarFastTiesRCPP <- function(xNumeric, yNumeric) {
    .Call('TauStar_TStarFastTiesRCPP', PACKAGE = 'TauStar', xNumeric, yNumeric)
}

VTStarFastTiesRCPP <- function(xNumeric, yNumeric) {
    .Call('TauStar_VTStarFastTiesRCPP', PACKAGE = 'TauStar', xNumeric, yNumeric)
}

TStarFastResampleRCPP <- function(xNumeric, yNumeric, numResamples, sampleSize) {
    .Call('TauStar_TStarFastResampleRCPP', PACKAGE = 'TauStar', xNumeric, yNumeric, numResamples, sampleSize)
}

TStarSlowTiesRCPP <- function(x, y, vStat) {
    .Call('TauStar_TStarSlowTiesRCPP', PACKAGE = 'TauStar', x, y, vStat)
}

